version: "3.9"

services: 
  ui:
    build:
      context: ./ui
    ports: 
      - "3000:3000"
    container_name: ui
    stdin_open: true
  api:
    build: 
      context: ./api
    container_name: api
    ports: 
      - "5000:5000"
    volumes:
      - ./api/:/usr/src/app/api
      - /usr/src/app/api/node_modules
      